-- MySQL dump for diskominfp (schema + sample data)
-- Generated by automation

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `perhatian_notifications`;
DROP TABLE IF EXISTS `pengaduans`;
DROP TABLE IF EXISTS `anggotas`;
DROP TABLE IF EXISTS `ketuas`;
DROP TABLE IF EXISTS `sessions`;
DROP TABLE IF EXISTS `password_reset_tokens`;
DROP TABLE IF EXISTS `users`;

-- users
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- password_reset_tokens
CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- sessions (simple representation)
CREATE TABLE `sessions` (
  `id` varchar(255) NOT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text,
  `payload` longtext NOT NULL,
  `last_activity` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ketuas
CREATE TABLE `ketuas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `kategori` enum('Aplikasi','Jaringan','Persandian') NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ketuas_username_unique` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- anggotas
CREATE TABLE `anggotas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `kategori` enum('Aplikasi','Jaringan','Persandian') DEFAULT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `anggotas_username_unique` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- pengaduans
CREATE TABLE `pengaduans` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `no_hp` varchar(30) DEFAULT NULL,
  `kategori` varchar(255) DEFAULT NULL,
  `judul` varchar(255) NOT NULL,
  `isi` text NOT NULL,
  `bukti_foto` varchar(255) DEFAULT NULL,
  `perlu_perhatian` tinyint(1) NOT NULL DEFAULT 0,
  `catatan_perhatian` text DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'baru',
  `ketua_id` bigint unsigned DEFAULT NULL,
  `anggota_id` bigint unsigned DEFAULT NULL,
  `ketua` varchar(255) DEFAULT NULL,
  `anggota` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pengaduans_ketua_id_foreign` (`ketua_id`),
  KEY `pengaduans_anggota_id_foreign` (`anggota_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- perhatian_notifications
CREATE TABLE `perhatian_notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `pengaduan_id` bigint unsigned NOT NULL,
  `ketua_id` bigint unsigned DEFAULT NULL,
  `message` text DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `perhatian_pengaduan_id_idx` (`pengaduan_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Foreign keys
ALTER TABLE `pengaduans`
  ADD CONSTRAINT `pengaduans_ketua_id_foreign` FOREIGN KEY (`ketua_id`) REFERENCES `ketuas` (`id`) ON DELETE SET NULL,
  ADD CONSTRAINT `pengaduans_anggota_id_foreign` FOREIGN KEY (`anggota_id`) REFERENCES `anggotas` (`id`) ON DELETE SET NULL;

ALTER TABLE `perhatian_notifications`
  ADD CONSTRAINT `perhatian_pengaduan_fk` FOREIGN KEY (`pengaduan_id`) REFERENCES `pengaduans` (`id`) ON DELETE CASCADE;

-- Sample data
-- bcrypt hash for 'password123' generated during dump creation
SET @PWD_HASH = '$2y$10$n6W3GFD1WZrOdKBZJlsi4uvSUZM.cWgktz/2yuUHAc3TogoqbQ2Yy';

INSERT INTO `ketuas` (`id`,`nama`,`username`,`password`,`kategori`,`created_at`,`updated_at`) VALUES
(1,'Ketua Aplikasi','ketua_aplikasi',@PWD_HASH,'Aplikasi',NOW(),NOW()),
(2,'Ketua Jaringan','ketua_jaringan',@PWD_HASH,'Jaringan',NOW(),NOW()),
(3,'Ketua Persandian','ketua_persandian',@PWD_HASH,'Persandian',NOW(),NOW());

-- Anggota from config (username pattern: lowercase with underscores + index)
INSERT INTO `anggotas` (`nama`,`username`,`password`,`kategori`,`created_at`,`updated_at`) VALUES
('Anggota Aplikasi 1','anggota_aplikasi_1',@PWD_HASH,'Aplikasi',NOW(),NOW()),
('Anggota Aplikasi 2','anggota_aplikasi_2',@PWD_HASH,'Aplikasi',NOW(),NOW()),
('Anggota Aplikasi 3','anggota_aplikasi_3',@PWD_HASH,'Aplikasi',NOW(),NOW()),
('Anggota Jaringan 1','anggota_jaringan_1',@PWD_HASH,'Jaringan',NOW(),NOW()),
('Anggota Jaringan 2','anggota_jaringan_2',@PWD_HASH,'Jaringan',NOW(),NOW()),
('Anggota Jaringan 3','anggota_jaringan_3',@PWD_HASH,'Jaringan',NOW(),NOW()),
('Anggota Persandian 1','anggota_persandian_1',@PWD_HASH,'Persandian',NOW(),NOW()),
('Anggota Persandian 2','anggota_persandian_2',@PWD_HASH,'Persandian',NOW(),NOW()),
('Anggota Persandian 3','anggota_persandian_3',@PWD_HASH,'Persandian',NOW(),NOW());

-- Sample pengaduans (one per category), note ketua/anggota assigned where appropriate
INSERT INTO `pengaduans` (`id`,`nama`,`email`,`no_hp`,`kategori`,`judul`,`isi`,`status`,`ketua_id`,`ketua`,`created_at`,`updated_at`) VALUES
(1,'Budi','budi@example.com','085600000001','Aplikasi','Aplikasi tidak bisa login','Saat mencoba login muncul error 500. Mohon ditindaklanjuti.','baru',1,'Ketua Aplikasi',NOW(),NOW()),
(2,'Siti','siti@example.com','085600000002','Jaringan','Internet sering putus','Koneksi sering terputus sejak kemarin sore.','baru',2,'Ketua Jaringan',NOW(),NOW()),
(3,'Agus','agus@example.com','085600000003','Persandian','Permintaan akses sandi','Butuh akses ke layanan sandi internal, mohon proses.','baru',3,'Ketua Persandian',NOW(),NOW());

-- Sample perhatian notification
INSERT INTO `perhatian_notifications` (`pengaduan_id`,`ketua_id`,`message`,`is_read`,`created_at`,`updated_at`) VALUES
(1,1,'Mohon tinjau pengaduan ini, dampak luas.',0,NOW(),NOW());

SET FOREIGN_KEY_CHECKS = 1;
